name: Website Uptime Monitor

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USERNAME_JULIUS: ${{ secrets.USERNAME_JULIUS }}
      PASSWORD_JULIUS: ${{ secrets.PASSWORD_JULIUS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to access all branches

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run uptime analysis
        run: npx ts-node analyse.ts

      - name: Commit and push updated uptime log
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin
          git checkout -B uptime-data
          git add uptime-log.json
          git commit -m "Update uptime log [skip ci]" || echo "No changes to commit"
          git push origin uptime-data
