name: Website Uptime Monitor

on:
  schedule:
    - cron: '0 * * * *'  # once per hour
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USERNAME_JULIUS: ${{ secrets.USERNAME_JULIUS }}
      PASSWORD_JULIUS: ${{ secrets.PASSWORD_JULIUS }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check permissions on playwright binary
        run: ls -l node_modules/.bin/playwright

      - name: Add execute permission if missing
        run: chmod +x node_modules/.bin/playwright

      - name: Verify permissions fixed
        run: ls -l node_modules/.bin/playwright

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run uptime analysis
        run: npx ts-node analyse.ts

      - name: Upload uptime report
        uses: actions/upload-artifact@v4
	uses: actions/download-artifact@v4
        with:
          name: uptime-report
          path: uptime-log.json


