name: Website Uptime Monitor

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USERNAME_JULIUS: ${{ secrets.USERNAME_JULIUS }}
      PASSWORD_JULIUS: ${{ secrets.PASSWORD_JULIUS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Make Playwright binary executable
        run: |
          chmod +x node_modules/.bin/playwright
          chmod +x node_modules/.bin/ts-node

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run uptime analysis and push to uptime-data branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          npx ts-node analyse.ts

          git checkout -b temp-uptime-update
          git commit -m "Update uptime log [skip ci]" || echo "No changes to commit"

          git add uptime-log.json

          git fetch origin uptime-data
          git checkout uptime-data
          git pull origin uptime-data

          git cherry-pick temp-uptime-update || echo "Nothing to cherry-pick"

          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:uptime-data
