name: Website Uptime Monitor

on:
  schedule:
    - cron: '0 * * * *'  # once per hour
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USERNAME_JULIUS: ${{ secrets.USERNAME_JULIUS }}
      PASSWORD_JULIUS: ${{ secrets.PASSWORD_JULIUS }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
