name: Website Uptime Monitor

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USERNAME_JULIUS: ${{ secrets.USERNAME_JULIUS }}
      PASSWORD_JULIUS: ${{ secrets.PASSWORD_JULIUS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download uptime log artifact if available
        uses: actions/download-artifact@v3
        with:
          name: uptime-log
          path: ./
        # This step will fail if the artifact does not exist yet,
        # so we ignore errors to allow first run without the file
        continue-on-error: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Make Playwright binary executable
        run: |
          chmod +x node_modules/.bin/playwright
          chmod +x node_modules/.bin/ts-node

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run uptime analysis
        run: npx ts-node analyse.ts

      - name: Upload uptime log artifact
        uses: actions/upload-artifact@v3
        with:
          name: uptime-log
          path: uptime-log.json
